using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MouseLook : MonoBehaviour
{
    public float mouseSensitivity = 100f;
    public Transform playerBody;
    int speed = 5;
    float xRotation = 0f;

    void Start()
    {
        Cursor.lockState = CursorLockMode.Locked; // 마우스를 화면 중앙에 고정
    }

    void Update()
    {
        float mouseX = Input.GetAxis("Mouse X") * mouseSensitivity * Time.deltaTime*speed;
        float mouseY = Input.GetAxis("Mouse Y") * mouseSensitivity * Time.deltaTime*speed;

        xRotation -= mouseY;
        xRotation = Mathf.Clamp(xRotation, -90f, 90f); // 위아래 회전 제한

        transform.localRotation = Quaternion.Euler(xRotation, 0f, 0f); // 카메라(위아래)
        playerBody.Rotate(Vector3.up * mouseX); // 플레이어 몸통(좌우)
    }
}